### ISSUE TITLE
Фогстрим ревью

### ISSUE THREAD

**Issue by nikvst** [gugry/fogstream_vacancy_task#1]
замечания по проекту

1. БД.
  - Должность и улицу не стоит заносить в одну таблицу, все таки это не связанные данные
  - Почему между Должность и Сотрудник связь "много-ко-многим"? В представленном примере сотрудник может занимать только одну должность

2. в репозитории отстутсивует .gitignore, из-за этого в проект попал мусор (__pycache__)

3. остались сгенерированные джанго файлы. Если они не используются (как tests.py в этом случае, то их нужно удалять)

4. Отсутствуют тесты

5. fogstream_vacancy_task/settings.py
```
DEBUG = True

SECRET_KEY = '(vmzk)2ds&fc=qlfum1z1qg&h$jm(=-^siwu^55h_o%4ec=wo-'

EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = "mailsender1251@yandex.ru"
EMAIL_HOST_PASSWORD = "fogstream"
EMAIL_USE_SSL = True
```
Всего этого не должно быть в релизной версии проета. Паролей и SECRET_KEY в принципе не должно быть в репозитории.
Нужно разделять общие настройки проекта и настройки для конкретного окружения, на котором проект будет запускаться.
https://hackernoon.com/4-ways-to-manage-the-configuration-in-python-4623049e841b

Также следует убирать настройки по умолчанию, если они не менялись (как и сгенерированные комментарии).
Достаточно заимпортить что-то вроде
`from django.conf.global_settings import *`.

6. fogstream_vacancy_task/urls.py
Требуется убирать стандартные комментарии

7. base_app/views.py
  - зачем импортируется from __future__ import unicode_literals? Тут используется python2?
  - следует группировать и сортировать импорты, для этого можно воспользоваться isort
  - reg_user содержит 4 return, следует стараться оставлять один return в конце функции, чтобы функцию было проще читать
  - для регистрации и авторизации следовало воспользоваться готовыми view django и просто поменять у них шаблон 
    (см. django.contrib.auth.views). 
    Один из возможных способов реализации - https://wsvincent.com/django-user-authentication-tutorial-login-and-logout/
  - reg_passwords_validate - зачем выполнять сравнение паролей на сервере, это задача для клиента
  - Зачем здесь дважды делать одно и тоже?)
        ```
            'equal': password_1 == password_2,
            'not_equal': password_1 != password_2,
        ```
  - reg_username_validate - Это следует проверять при регистрации в reg_user
  - два одинаковых действия приведут к двум запросам к базе вместо одного
        ```
            'is_taken': User.objects.filter(username__iexact=username).exists(),
            'is_free': not User.objects.filter(username__iexact=username).exists()}
        ```
  - message_for_admin - сейчас сообщение может отправить кто угодно, не только авторизованный пользователь
  - `except BaseException as err:` - следует перехватывать более осмысленные классы ошибок

7. base_app/models.py
  - отсутствуют verbose_name у полей и у модели

**Comment by gugry** [comment]
1. БД
	- Согласно тем данным, которые есть, улица зависит только от должности и не зависит от других данных. Как следует поступать в подобном случае?
	- Иванову Ивану Ивановичу соответствует Должность 1, Должность 2 и Должность 3. Предполагается, что могут быть разные сотрудники с одним ФИО?

3. Остались сгенерированные джанго файлы. Если они не используются (как tests.py в этом случае, то их нужно удалять)
	После добавления тестов tests.py используется. Больше не смог найти неиспользуемых файлов

5. settings.py 
	Не смог найти настроек, которые бы не были переопределены относительно django.conf.global_settings

7. base_app/views.py
	- reg_user содержит 4 return, следует стараться оставлять один return в конце функции, чтобы функцию было проще читать
		Поправил, но на мой взгляд в изначальном варианте было удобней
	- для регистрации и авторизации следовало воспользоваться готовыми view django и просто поменять у них шаблон
		Поправил. Но в этом варианте не работают ассинхронные запросы
	- except BaseException as err: - следует перехватывать более осмысленные классы ошибок
		В данном случае рассчет именно на перехват любой ошибки. И, если таковая возникает, внесение соответствующей пометки, согласно заданию.
		Не представляю, как можно это реализовать по другому.
